import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import profileRouter from "./profile.js";
import missionsRouter from "./missions.js";
import missionTemplatesRouter from "./mission-templates.js";
import quotesRouter from "./quotes.js";
import journalRouter from "./journal.js";
import ideasRouter from "./ideas.js";
import checklistRouter from "./checklist.js";
import newsRouter from "./news.js";
import settingsRouter from "./settings.js";
import friendsRouter from "./friends.js";
import chatRouter from "./chat.js";
import calendarRouter from "./calendar.js";
import backtestRouter from "./backtest.js";
import candlesRouter from "./candles.js";
import checkinsRouter from "./checkins.js";
import toolsRouter from "./tools.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(profileRouter);
router.use(missionsRouter);
router.use(missionTemplatesRouter);
router.use(quotesRouter);
router.use(journalRouter);
router.use(ideasRouter);
router.use(checklistRouter);
router.use(newsRouter);
router.use(settingsRouter);
router.use(friendsRouter);
router.use(chatRouter);
router.use(calendarRouter);
router.use(backtestRouter);
router.use(candlesRouter);
router.use(checkinsRouter);
router.use(toolsRouter);

export default router;
